import Foundation
import SwiftData

@Model
public final class Trip {
    public var id: UUID
    public var name: String
    public var startDate: Date
    public var endDate: Date
    public var destinationName: String
    public var destinationLatitude: Double?
    public var destinationLongitude: Double?

    /// JPEG/PNG bytes of an optional cover photo selected via PhotosPicker.
    /// Compressed to ~512KB max before storing.
    @Attribute(.externalStorage)
    public var coverPhotoData: Data?

    /// Free-form packing checklist for the trip. Stored as a single value-type
    /// array so we can persist without introducing a new @Model.
    public var packingItems: [PackingItem]

    /// Round-12 slice 9: free-form Markdown notes attached to the trip.
    /// Rendered via `Text(LocalizedStringKey)` so basic Markdown (bold, links)
    /// works without a third-party renderer.
    public var notes: String = ""

    /// Round-12 slice 10: snapshot of the user's recent currency conversions
    /// captured at trip end. Stored as JSON string of `RecentConversionsStore.Entry`
    /// array so we don't need a new schema migration. `nil` until set.
    public var currencySnapshotJSON: String?

    /// Round-13 slice 10: free-form expense log captured during the trip.
    /// JSON-encoded array of `TripExpense` so we don't add a new @Model.
    public var expensesJSON: String?

    /// Round-14 slice 14: emergency contacts attached to the trip. JSON-
    /// encoded `[TripEmergencyContact]` to avoid another schema migration.
    public var emergencyContactsJSON: String?

    /// Round 27 (WS-A): persisted answers from the AI-itinerary wizard.
    /// JSON-encoded `TripItineraryRequest` so we don't add a new @Model.
    /// `nil` = wizard never ran for this trip.
    public var itineraryRequestJSON: String?

    /// Round 29 (Wizard v2): last text generated by Apple Foundation Models
    /// for this trip. `nil` when the on-device path has not been run.
    public var itineraryGeneratedText: String?

    /// Round 29 (Wizard v2): timestamp of `itineraryGeneratedText`.
    public var itineraryGeneratedAt: Date?

    @Relationship(deleteRule: .cascade, inverse: \TripMilestone.trip)
    public var milestones: [TripMilestone]

    @Relationship(deleteRule: .cascade, inverse: \TripDocument.trip)
    public var documents: [TripDocument]

    public init(
        id: UUID = UUID(),
        name: String,
        startDate: Date,
        endDate: Date,
        destinationName: String,
        destinationLatitude: Double? = nil,
        destinationLongitude: Double? = nil,
        coverPhotoData: Data? = nil,
        packingItems: [PackingItem] = [],
        milestones: [TripMilestone] = [],
        documents: [TripDocument] = [],
        notes: String = "",
        currencySnapshotJSON: String? = nil,
        expensesJSON: String? = nil,
        emergencyContactsJSON: String? = nil,
        itineraryRequestJSON: String? = nil,
        itineraryGeneratedText: String? = nil,
        itineraryGeneratedAt: Date? = nil
    ) {
        self.id = id
        self.name = name
        self.startDate = startDate
        self.endDate = endDate
        self.destinationName = destinationName
        self.destinationLatitude = destinationLatitude
        self.destinationLongitude = destinationLongitude
        self.coverPhotoData = coverPhotoData
        self.packingItems = packingItems
        self.milestones = milestones
        self.documents = documents
        self.notes = notes
        self.currencySnapshotJSON = currencySnapshotJSON
        self.expensesJSON = expensesJSON
        self.emergencyContactsJSON = emergencyContactsJSON
        self.itineraryRequestJSON = itineraryRequestJSON
        self.itineraryGeneratedText = itineraryGeneratedText
        self.itineraryGeneratedAt = itineraryGeneratedAt
    }
}

/// Round-12 slice 7: packing categories so the user can filter the list by
/// type while packing (clothing, electronics, docs, toiletries, other).
/// Optional with a default of `.other` so existing items deserialize cleanly.
public enum PackingCategory: String, Codable, CaseIterable, Sendable {
    case clothing
    case electronics
    case documents
    case toiletries
    case medication
    case other

    public var systemImage: String {
        switch self {
        case .clothing: "tshirt"
        case .electronics: "cable.connector"
        case .documents: "doc.text"
        case .toiletries: "drop.fill"
        case .medication: "pills"
        case .other: "cube.box"
        }
    }
}

/// A line in the trip packing list. Value type so the parent `Trip` `@Model`
/// owns the collection without needing a child `@Model` table.
public struct PackingItem: Codable, Hashable, Sendable, Identifiable {
    public var id: UUID
    public var title: String
    public var isPacked: Bool
    /// Round-12 slice 7: optional category. Persists as a string raw value
    /// inside the parent `Trip`'s `packingItems` array; older items decode
    /// to `.other` via the explicit default-on-decode path.
    public var category: PackingCategory

    public init(
        id: UUID = UUID(),
        title: String,
        isPacked: Bool = false,
        category: PackingCategory = .other
    ) {
        self.id = id
        self.title = title
        self.isPacked = isPacked
        self.category = category
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.title = try container.decode(String.self, forKey: .title)
        self.isPacked = try container.decode(Bool.self, forKey: .isPacked)
        self.category = try container.decodeIfPresent(PackingCategory.self, forKey: .category) ?? .other
    }
}
